[package]
name = "frink"
version = "0.1.0"
edition = "2021"

[dependencies]
alphred = "0.1.11"
anyhow = { version = "1.0.56", features = ["backtrace"] }
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["blocking"] }
